### ISSUE TITLE
Image build - not every 6 hours (latest update: 2 month ago)

### ISSUE THREAD

**Issue by SnickCH** [steamcmd/docker#54]
Hi

Thank you very much for providing the images. The description says that the images are rebuilt every 6 hours. I checked the docker-hub repository and saw that the last update was 2 months ago. Therefore I'm opening an issue - so you have the information about the last update time. 

Best regards

**Comment by jonakoudijs** [comment]
Hi Snick,

Thanks a lot for opening an issue for this. I was not aware the scheduled workflows/pipeline stopped running. Apparently it stops after 60 days without activity in the repository:

![scheduled-workflows-warning](https://user-images.githubusercontent.com/1906344/144601275-5a1f9f98-b529-4958-a4f9-0e68f5d9e1d8.png)

Strange that I never got a notification about this.. I have re-enabled the workflow and will look for a solution for it. Probably creating some monitoring for this would be a nice enhancement as well. If you have any suggestions, don't hesitate to share them :)

Thanks again for your contribution!

Greetings,
Jona

**Comment by SnickCH** [comment]
Hi Jona

Thank you very much for your fast reply. 

I use gitlab for the pipeline of my images (daily/weekly). There I receive a mail if something failes on the pipeline
https://docs.gitlab.com/ee/user/profile/notifications.html

What tool(s) are you using for your pipeline? Maybe I can help you looking for a solution
Best regards
Snick

**Comment by jonakoudijs** [comment]
Hi Snick,

The SteamCMD project uses Github Actions to test, build and push the Docker images. The actions config can be found here: https://github.com/steamcmd/docker/tree/master/.github/workflows and the (history of the) pipelines here: https://github.com/steamcmd/docker/actions.

Normally I do receive notifications for failed pipelines but because Github decided to automatically suspend the pipelines I did not receive any notification.

When looking at the Actions documentation it seems this is default behaviour and there is not official way to disable this. Perhaps a (dirty) work-around can be used like: https://github.com/gautamkrishnar/keepalive-workflow. I will have to test with this some more later.

Greetings,
Jona

**Comment by SnickCH** [comment]
Hi Jona

Disclaymer: I work with gitlab, therefore I have to experience with the github actions. 

I took a look at the documentation and the workaround. I guess you have to use the workaround or make a manual commit, as long as github has the 60days limitation.

Greetings,
Snick

**Comment by jonakoudijs** [comment]
Hi Snick,

Thanks for your help so far and thinking along. I added the Keepalive Workflow I mentioned earlier in pull request: https://github.com/steamcmd/docker/pull/55. Besides this change I am thinking about implementing a monitoring endpoint that checks for outdated Docker images, Steam status etc. but this is something for the long run.

Greetings,
Jona
