### ISSUE TITLE
Alpine image doesn't run CS2

### ISSUE THREAD

**Issue by thetredev** [steamcmd/docker#68]
I can successfully install CS2 (AppID 730) but it won't start:
```
$ docker inspect steamcmd/steamcmd:alpine-3 
[
    {
        "Id": "sha256:3f0c8c559c50a9c78eda0a91d1f4628924142830ad1a600d78efb21c8699535a",
        "RepoTags": [
            "steamcmd/steamcmd:alpine-3"
        ],
        "RepoDigests": [
            "steamcmd/steamcmd@sha256:62d2ac729b313a3ffa9f827b9cf81daf6b625ff55f2b3eb05f3c2980ddffbd65"
        ],
....
```
```
$ docker run --rm -p 27015:27015/udp --entrypoint bash -v /tmp/cs2:/cs2 -it steamcmd/steamcmd:alpine-3
384a94ad33fa:~# steamcmd +force_install_dir /cs2 +login anonymous +app_update 730 validate +quit
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...

...................

 Update state (0x5) verifying install, progress: 89.77 (31878365195 / 35509481818)
 Update state (0x5) verifying install, progress: 93.80 (33306457436 / 35509481818)
 Update state (0x5) verifying install, progress: 97.73 (34703327306 / 35509481818)
Success! App '730' fully installed.
```
```
384a94ad33fa:~# /cs2/game/bin/linuxsteamrt64/cs2 -dedicated -ip 0.0.0.0 +map de_dust2
bash: /cs2/game/bin/linuxsteamrt64/cs2: cannot execute: required file not found
```

Haven't tried the Ubuntu or Rocky ones, but I assume they work because of (64 bit) `glibc`.

**Comment by jonakoudijs** [comment]
Your assumption might be right. There are a few packages that normally need to be installed for CS2 to work. Also CS(2) depends on a few libraries that might be already included in Ubuntu but not on Alpine. In my personal experience I would start by using Ubuntu or Debian when running these kind of game servers and try Alpine later if you really want to go down that route.

**Comment by thetredev** [comment]
@jonakoudijs I was actually hoping for a fix. Am I right to assume this is not gonna be addressed any time soon?

**Comment by jonakoudijs** [comment]
Required libraries or alternative C libraries that are needed by a specific gameserver is not something that will be included in these Docker images. Every game server has different decencies and it's next to impossible include all of them by default in these base images.

It's by design that these images contain only the most recent **steamcmd** and no extra packages. It's the user's responsibility to add the required extra packages needed for a specific game server when installing it.

All that being said I am not sure if it's even possible to get it working on Alpine. The CS2 Linux software depends on glibc and if though Alpine has a C library in the form of [musl](https://musl.libc.org) it is not the same and your success may vary. The [Alpine wiki](https://wiki.alpinelinux.org/wiki/Running_glibc_programs) mentions a compatibility layer that can be installed called ** gcompat**. You could you try that but I never used it myself.

**Comment by thetredev** [comment]
Thanks for the explanation! I tried `gcompat` but to no avail. Seems like Alpine/musl is out of the question then.
